import { FeedSource } from "@/lib/types";

export const FEED_SOURCES: FeedSource[] = [
  {
    id: "clarin_ciudad",
    title: "Clarín · Ciudades",
    feedUrl: "https://www.clarin.com/rss/ciudades/",
    topic: "Política y Gobierno",
    region: "CABA",
  },
  {
    id: "clarin_politica",
    title: "Clarín · Política",
    feedUrl: "https://www.clarin.com/rss/politica/",
    topic: "Política y Gobierno",
    region: "CABA",
  },
  {
    id: "lanacion_politica",
    title: "La Nación · Política",
    feedUrl: "https://www.lanacion.com.ar/politica/rss/",
    topic: "Política y Gobierno",
    region: "CABA",
  },
  {
    id: "lanacion_outbound",
    title: "La Nación · Últimas",
    feedUrl: "https://www.lanacion.com.ar/arc/outboundfeeds/rss/?outputType=xml",
    topic: "Política y Gobierno",
    region: "CABA",
  },
  {
    id: "pagina12_economia",
    title: "Página/12 · Economía",
    feedUrl: "https://www.pagina12.com.ar/rss/secciones/economia/notas",
    topic: "Economía",
    region: "CABA",
  },
  {
    id: "ambito_finanzas",
    title: "Ámbito · Finanzas",
    feedUrl: "https://www.ambito.com/rss/finanzas.xml",
    topic: "Economía",
    region: "CABA",
  },
  {
    id: "cronista_negocios",
    title: "El Cronista · Negocios",
    feedUrl: "https://www.cronista.com/rss/negocios/",
    topic: "Negocios",
    region: "CABA",
  },
  {
    id: "iprofesional_tecnologia",
    title: "iProfesional · Tecnología",
    feedUrl: "https://www.iprofesional.com/rss/tecnologia",
    topic: "Tecnología",
    region: "CABA",
  },
  {
    id: "infobae_argentina",
    title: "Infobae · Argentina",
    feedUrl: "https://www.infobae.com/arc/outboundfeeds/rss/argentina/",
    topic: "Política y Gobierno",
    region: "CABA",
  },
  {
    id: "tn_ultimas",
    title: "TN · Últimas",
    feedUrl:
      "https://www.tn.com.ar/arc/outboundfeeds/google-news-feed/?outputType=xml",
    topic: "Política y Gobierno",
    region: "CABA",
  },
  {
    id: "infocielo_provincia",
    title: "Infocielo · Provincia",
    feedUrl: "https://www.infocielo.com/feed",
    topic: "Política y Gobierno",
    region: "PBA",
  },
  {
    id: "infoplatense_la_plata",
    title: "Infoplatense · La Plata",
    feedUrl: "https://www.infoplatense.com.ar/feed/",
    topic: "Política y Gobierno",
    region: "PBA",
  },
  {
    id: "diagonales_provincia",
    title: "Diagonales · Provincia",
    feedUrl: "https://www.diagonales.com/rss",
    topic: "Política y Gobierno",
    region: "PBA",
  },
];
