import { PopularNewsTab, StoryCluster } from "./types";

export const MOCK_CLUSTERS: StoryCluster[] = [
  // 1) Transporte & Movilidad – buen candidato para Top Story
  {
    id: "cluster_subte_dic_2025",
    createdAt: "2025-11-17T07:30:00Z",
    headline: "El SUBTE aumentará 15% desde diciembre en toda la red",
    subtitle:
      "La Ciudad actualiza la tarifa en un contexto de inflación alta y presión sobre los subsidios.",
    summary:
      "El Gobierno porteño confirmó un aumento del 15% en la tarifa del subte desde el 10 de diciembre. La medida impactará a más de tres millones de pasajeros diarios y se suma a los incrementos registrados durante el año.",
    bullets: [
      "La tarifa pasará de $130 a $150 en todas las líneas.",
      "La Ciudad argumenta que el ajuste responde a mayores costos operativos y energéticos.",
      "Organizaciones de usuarios cuestionan el impacto acumulado en el bolsillo.",
      "Desde Nación presionan para reducir los subsidios al transporte en el AMBA.",
    ],
    body: "El Gobierno de la Ciudad de Buenos Aires anunció un aumento del 15% en la tarifa del subte a partir del 10 de diciembre. Según las autoridades porteñas, la medida busca actualizar los ingresos del servicio frente a mayores costos operativos, especialmente en energía y salarios. El incremento se aplicará en todas las líneas y afectará a más de tres millones de pasajeros diarios que utilizan la red. Organizaciones de usuarios criticaron el impacto acumulado de los aumentos en el contexto inflacionario, mientras que desde Nación se mantiene la presión para reducir los subsidios destinados al transporte en el AMBA.",
    image: "https://example.com/images/subte-aumento.jpg",
    topic: "Transporte & Movilidad",
    bias: { left: 28, center: 50, right: 22 },
    sources: [
      {
        id: "ln_subte_dic",
        source: "La Nación",
        title: "El subte tendrá un aumento del 15% desde diciembre",
        description:
          "El Gobierno porteño justificó la suba por el aumento de costos.",
        url: "https://lanacion.com.ar/politica/subte-aumento-diciembre",
        image: "https://example.com/images/ln-subte.jpg",
        publishedAt: "2025-11-17T06:40:00Z",
        text: "El Gobierno de la Ciudad confirmó un aumento del 15% en la tarifa del subte desde el 10 de diciembre...",
      },
      {
        id: "clarin_subte_dic",
        source: "Clarín",
        title: "Nuevo aumento del subte en la Ciudad: cómo quedan las tarifas",
        description: "",
        url: "https://clarin.com/ciudad/subte-nuevo-aumento-tarifas",
        image: "https://example.com/images/ambito-inflacion.jpg",
        publishedAt: "2025-11-17T07:05:00Z",
        text: "La tarifa del subte pasará de $130 a $150 a partir del próximo mes, según informaron fuentes oficiales...",
      },
      {
        id: "p12_subte_dic",
        source: "Página/12",
        title: "Otro tarifazo en el subte porteño",
        description:
          "El Gobierno porteño justificó la suba por el aumento de costos.",
        url: "https://pagina12.com.ar/economia/tarifazo-subte-porteno",
        image: "https://example.com/images/ambito-inflacion.jpg",
        publishedAt: "2025-11-17T07:20:00Z",
        text: "El nuevo aumento del subte se enmarca en una serie de incrementos que golpean el bolsillo de los usuarios...",
      },
    ],
    tags: ["SUBTE", "Tarifas", "AMBA", "Transporte"],
  },

  // 2) Economía & Precios – buen candidato para Briefing
  {
    id: "cluster_inflacion_oct_2025",
    createdAt: "2025-11-17T07:35:00Z",
    headline: "La inflación de octubre fue 8,1% y acumula 176% en el año",
    subtitle:
      "El dato refleja una leve desaceleración, pero se mantiene en niveles muy altos para los hogares del AMBA.",
    summary:
      "El INDEC informó que la inflación de octubre fue del 8,1%, levemente por debajo del registro de septiembre. Sin embargo, la suba de precios acumula 176% en lo que va del año y sigue golpeando con fuerza a los alimentos y servicios en el AMBA.",
    bullets: [
      "Alimentos y bebidas aumentaron por encima del índice general.",
      "Los servicios regulados, como luz y gas, aportaron presión al índice.",
      "Analistas prevén que la desaceleración será lenta si no hay cambios de fondo.",
      "En el AMBA, los alquileres y el transporte siguen siendo los rubros más sensibles.",
    ],
    body: "El INDEC dio a conocer que la inflación de octubre fue del 8,1%, lo que implica una leve desaceleración respecto al mes anterior, aunque se mantiene en niveles muy elevados. De esta manera, el índice de precios al consumidor acumula un 176% en lo que va del año. Los alimentos y bebidas volvieron a ubicarse por encima del promedio, afectando especialmente a los hogares de menores ingresos en el Área Metropolitana de Buenos Aires. Los ajustes en tarifas de servicios regulados, como luz y gas, también presionaron el indicador. Especialistas advierten que, sin un cambio consistente en la política económica, la baja en la inflación será gradual y no se reflejará rápidamente en la calle. En el AMBA, los alquileres, el transporte y los servicios básicos siguen liderando las preocupaciones cotidianas de los vecinos.",
    image: "https://example.com/images/supermercado-inflacion.jpg",
    topic: "Economía & Precios",
    bias: { left: 35, center: 45, right: 20 },
    sources: [
      {
        id: "ambito_inflacion_oct",
        source: "Ámbito",
        title: "La inflación de octubre fue 8,1% y suma 176% en el año",
        description: "El INDEC confirmó una leve desaceleración del índice.",
        url: "https://ambito.com/economia/inflacion-octubre",
        image: "https://example.com/images/ambito-inflacion.jpg",
        publishedAt: "2025-11-16T21:00:00Z",
        text: "El INDEC informó que la inflación de octubre se ubicó en el 8,1%, acumulando 176% en los primeros diez meses del año...",
      },
      {
        id: "cronista_inflacion_oct",
        source: "El Cronista",
        title: "Inflación: qué pasó en octubre y qué se espera para noviembre",
        description: "",
        url: "https://cronista.com/economia/inflacion-octubre-que-esperar",
        image: null,
        publishedAt: "2025-11-17T01:20:00Z",
        text: "Con un registro del 8,1% en octubre, la inflación muestra una leve baja, aunque los analistas advierten...",
      },
    ],
    tags: ["Inflación", "Precios", "INDEC"],
  },

  // 3) Seguridad – típica nota muy “clickable” en BA
  {
    id: "cluster_inseguridad_palermo_noche",
    createdAt: "2025-11-17T07:40:00Z",
    headline: "Aumentan las denuncias por robos nocturnos en Palermo",
    subtitle:
      "Vecinos reclaman más presencia policial en zonas gastronómicas y corredores nocturnos.",
    summary:
      "En las últimas semanas se registró un incremento de denuncias por robos y arrebatos en el barrio de Palermo, especialmente en horarios nocturnos. Comerciantes y vecinos señalan que la zona de bares y restaurantes se volvió más insegura y piden refuerzos de la Policía de la Ciudad.",
    bullets: [
      "Las denuncias crecieron principalmente en fines de semana.",
      "Los hechos se concentran alrededor de polos gastronómicos y calles muy transitadas.",
      "Vecinos exigen más patrullajes a pie y controles de motos.",
      "El Gobierno porteño promete operativos focalizados y coordinación con fiscalías.",
    ],
    body: "Vecinos y comerciantes de Palermo reportaron un aumento de robos y arrebatos durante la noche en las últimas semanas, sobre todo en las zonas de mayor concentración de bares y restaurantes. De acuerdo con datos oficiales y relevamientos vecinales, los hechos se incrementan los fines de semana y suelen involucrar a motochorros o grupos que aprovechan la salida de locales gastronómicos. Los reclamos apuntan a la necesidad de una mayor presencia policial a pie y patrulleros tanto en calles internas como en avenidas principales. Desde el Gobierno de la Ciudad señalan que se reforzarán los operativos en los corredores nocturnos del barrio y se trabajará en conjunto con las fiscalías para agilizar las denuncias.",
    image: "https://example.com/images/palermo-noche.jpg",
    topic: "Seguridad",
    bias: { left: 25, center: 50, right: 25 },
    sources: [
      {
        id: "tn_palermo_robos",
        source: "TN",
        title:
          "Preocupación en Palermo por aumento de robos a la salida de bares",
        description: "Vecinos piden más presencia policial.",
        url: "https://tn.com.ar/sociedad/robos-palermo-noches",
        image: "https://example.com/images/tn-palermo.jpg",
        publishedAt: "2025-11-16T23:30:00Z",
        text: "En las últimas semanas se registró un aumento de robos en la zona de bares de Palermo, según denunciaron vecinos...",
      },
      {
        id: "infobae_palermo_robos",
        source: "Infobae",
        title: "Más robos en Palermo: comerciantes reclaman controles",
        description: "",
        url: "https://infobae.com/sociedad/robos-palermo-gastronomia",
        image: null,
        publishedAt: "2025-11-17T06:10:00Z",
        text: "Los comerciantes de Palermo aseguran que los hechos de inseguridad aumentaron en el último mes y que la situación preocupa...",
      },
    ],
    tags: ["Palermo", "Inseguridad", "AMBA"],
  },

  // 4) Gobierno de la Ciudad – medida concreta
  {
    id: "cluster_gob_caba_espacios_verdes",
    createdAt: "2025-11-17T07:45:00Z",
    headline: "La Ciudad suma un nuevo parque lineal en la zona sur",
    subtitle:
      "El proyecto apunta a recuperar el espacio público y mejorar la conexión peatonal en Barracas y Parque Patricios.",
    summary:
      "El Gobierno porteño presentó un nuevo parque lineal en la zona sur de la Ciudad, con circuitos peatonales, bicisendas y áreas de juego. El objetivo es ampliar la superficie de espacios verdes y mejorar la integración urbana en barrios históricamente postergados.",
    bullets: [
      "El parque lineal se extenderá a lo largo de ex terrenos ferroviarios.",
      "Incluye bicisendas, juegos para chicos y mobiliario urbano.",
      "Vecinos valoran el proyecto pero piden garantizar mantenimiento y seguridad.",
      "Organizaciones barriales cuestionan el proceso de consulta previa.",
    ],
    body: "El Gobierno de la Ciudad de Buenos Aires anunció la creación de un nuevo parque lineal en la zona sur, que se desarrollará sobre antiguos terrenos ferroviarios entre Barracas y Parque Patricios. El proyecto contempla la incorporación de bicisendas, senderos peatonales, áreas de juego y mobiliario urbano, con el objetivo de ampliar la superficie de espacios verdes accesibles para los vecinos. Desde el Ejecutivo porteño destacan que la iniciativa apunta a equilibrar la oferta de espacios públicos en relación con el norte de la Ciudad. Vecinos y organizaciones barriales reconocen el impacto positivo de sumar verde, pero señalan la necesidad de garantizar mantenimiento, iluminación y seguridad en la zona, así como una mayor participación en el diseño final.",
    image: "https://example.com/images/parque-lineal-sur.jpg",
    topic: "Gobierno de la Ciudad",
    bias: { left: 30, center: 55, right: 15 },
    sources: [
      {
        id: "ln_parque_lineal_sur",
        source: "La Nación",
        title: "La Ciudad proyecta un nuevo parque lineal en la zona sur",
        description: "El Gobierno porteño busca sumar espacios verdes.",
        url: "https://lanacion.com.ar/ciudad/parque-lineal-zona-sur",
        image: "https://example.com/images/ln-parque.jpg",
        publishedAt: "2025-11-16T15:10:00Z",
        text: "La administración porteña anunció la construcción de un parque lineal en la zona sur, sobre terrenos ferroviarios en desuso...",
      },
      {
        id: "pagina12_parque_lineal_sur",
        source: "Página/12",
        title: "Nuevo parque lineal: vecinos piden más participación",
        description:
          "El Gobierno porteño justificó la suba por el aumento de costos.",
        url: "https://pagina12.com.ar/sociedad/parque-lineal-sur-participacion",
        image: null,
        publishedAt: "2025-11-17T01:05:00Z",
        text: "Organizaciones barriales plantearon la necesidad de un proceso participativo para definir el uso del nuevo parque...",
      },
    ],
    tags: ["Espacios verdes", "Zona Sur", "Urbanismo"],
  },

  // 5) Provincia de Buenos Aires – algo fuerte para GBA
  {
    id: "cluster_pba_docentes_paro",
    createdAt: "2025-11-17T07:50:00Z",
    headline:
      "Docentes bonaerenses anuncian paro de 48 horas la próxima semana",
    subtitle:
      "Reclaman una mejora salarial por encima de la inflación y mayor inversión en infraestructura escolar.",
    summary:
      "Los gremios docentes de la provincia de Buenos Aires convocaron a un paro de 48 horas para la próxima semana tras considerar insuficiente la última oferta salarial del gobierno provincial. La medida afectará a miles de escuelas en el conurbano y el interior.",
    bullets: [
      "Los sindicatos piden una recomposición que supere la inflación acumulada.",
      "El Gobierno bonaerense afirma que la propuesta es “fiscalmente posible”.",
      "Familias del conurbano expresan preocupación por la cantidad de días sin clases.",
      "Habrá una nueva reunión paritaria luego del paro.",
    ],
    body: "Los principales gremios docentes de la provincia de Buenos Aires convocaron a un paro de 48 horas para la próxima semana, luego de rechazar la última propuesta salarial del Gobierno encabezado por el gobernador bonaerense. Los sindicatos reclaman una recomposición que supere la inflación acumulada y advierten sobre el deterioro de los salarios frente al aumento del costo de vida. Desde la administración provincial sostienen que la oferta presentada es la máxima posible en el marco de la situación fiscal actual. La medida de fuerza afectará a miles de escuelas en el conurbano y en el interior de la provincia, generando preocupación entre las familias por la continuidad del ciclo lectivo. Tras el paro, las partes volverían a reunirse en una nueva mesa paritaria.",
    image: "https://example.com/images/docentes-paro-pba.jpg",
    topic: "Provincia de Buenos Aires",
    bias: { left: 40, center: 45, right: 15 },
    sources: [
      {
        id: "clarin_pba_paro_docente",
        source: "Clarín",
        title: "Paro docente de 48 horas en Provincia: cuándo y por qué",
        description: "",
        url: "https://clarin.com/sociedad/paro-docente-provincia-48-horas",
        image: null,
        publishedAt: "2025-11-16T18:00:00Z",
        text: "Los gremios docentes convocaron a un paro de 48 horas en reclamo de una mejora salarial...",
      },
      {
        id: "pagina12_pba_paro_docente",
        source: "Página/12",
        title: "Los docentes bonaerenses paran por 48 horas",
        description:
          "El Gobierno porteño justificó la suba por el aumento de costos.",
        url: "https://pagina12.com.ar/sociedad/docentes-bonaerenses-paro",
        image: null,
        publishedAt: "2025-11-16T20:30:00Z",
        text: "Los gremios reclamaron una recomposición salarial por encima de la inflación y mejor infraestructura escolar...",
      },
    ],
    tags: ["Provincia de Buenos Aires", "Educación", "Paritaria docente"],
  },

  // 6) Servicios & Tarifas – muy relevante para AMBA
  {
    id: "cluster_luz_aumento_amba",
    createdAt: "2025-11-17T07:55:00Z",
    headline: "Aumentan hasta 12% las tarifas de luz en el AMBA desde enero",
    subtitle:
      "La suba impactará de forma escalonada según el nivel de consumo y el esquema de subsidios vigente.",
    summary:
      "El Ente Regulador anunció una actualización de hasta 12% en las tarifas de energía eléctrica para usuarios residenciales del AMBA a partir de enero. El aumento variará según el nivel de consumo y la categoría de subsidios, con mayor impacto en los hogares de ingresos medios.",
    bullets: [
      "La suba se aplicará en forma escalonada durante el primer trimestre.",
      "Los usuarios con mayor consumo verán los incrementos más altos.",
      "Organizaciones de consumidores cuestionan la falta de previsibilidad.",
      "El Gobierno argumenta que el ajuste es necesario para sostener el sistema energético.",
    ],
    body: "El organismo regulador de la energía informó una actualización de hasta el 12% en las tarifas eléctricas para usuarios residenciales del Área Metropolitana de Buenos Aires a partir de enero. La suba se aplicará de manera escalonada durante el primer trimestre del año y variará según el nivel de consumo y la categoría de subsidios que reciba cada hogar. Los usuarios con consumos más altos y menores niveles de subsidio serán los más afectados por el incremento. Asociaciones de consumidores cuestionaron la magnitud de la suba y advirtieron sobre la falta de previsibilidad para planificar gastos en un contexto de alta inflación. Desde el Gobierno sostienen que la actualización es necesaria para garantizar la sostenibilidad del sistema energético y reducir el peso de los subsidios en las cuentas públicas.",
    image: "https://example.com/images/medidor-luz.jpg",
    topic: "Servicios & Tarifas",
    bias: { left: 32, center: 48, right: 20 },
    sources: [
      {
        id: "ambito_luz_aumento",
        source: "Ámbito",
        title: "Tarifas de luz: suba de hasta 12% para el AMBA desde enero",
        description: "",
        url: "https://ambito.com/economia/tarifas-luz-amba-enero",
        image: null,
        publishedAt: "2025-11-16T19:45:00Z",
        text: "El ente regulador de la electricidad anunció una suba de hasta el 12% en las tarifas residenciales del AMBA...",
      },
      {
        id: "infobae_luz_aumento",
        source: "Infobae",
        title: "Luz más cara desde enero: quiénes pagarán más",
        description: "",
        url: "https://infobae.com/economia/luz-mas-cara-enero",
        image: null,
        publishedAt: "2025-11-17T06:50:00Z",
        text: "El aumento en las tarifas de luz impactará con más fuerza en los usuarios de ingresos medios y altos...",
      },
    ],
    tags: ["Tarifas", "Luz", "AMBA", "Servicios"],
  },
  {
    id: "cluster_gba_basura",
    createdAt: "2025-11-17T08:00:00Z",
    headline: "Municipios del GBA refuerzan recolección de basura post temporal",
    subtitle: "Los intendentes coordinan operativos especiales tras el temporal del fin de semana.",
    summary:
      "Tras las lluvias y ráfagas de viento en el AMBA, varios municipios desplegaron operativos especiales para retirar ramas y residuos, trabajando con cooperativas barriales para normalizar el servicio antes del próximo fin de semana.",
    bullets: [
      "El temporal dejó árboles caídos en más de 200 esquinas.",
      "Los intendentes pidieron paciencia por la saturación de los servicios.",
      "Se reforzó el personal nocturno y los camiones compactadores.",
      "Habrá puntos verdes móviles para residuos voluminosos.",
    ],
    body: "",
    image: "https://example.com/images/gba-basura.jpg",
    topic: "Gobierno de la Ciudad",
    bias: { left: 32, center: 48, right: 20 },
    sources: [
      {
        id: "infobae_gba_basura",
        source: "Infobae",
        title: "Temporal en el AMBA: cómo trabajan los municipios para limpiar las calles",
        description: "",
        url: "https://infobae.com/sociedad/temporal-operativos-gba",
        image: null,
        publishedAt: "2025-11-17T07:30:00Z",
        text: "Intendentes del conurbano explicaron los refuerzos de recolección tras el temporal...",
      },
    ],
    tags: ["Temporal", "Residuos", "AMBA"],
  },
  {
    id: "cluster_learn_ai",
    createdAt: "2025-11-17T08:15:00Z",
    headline: "La Ciudad abre un centro para capacitar en IA aplicada a PYMES",
    subtitle: "El nuevo centro busca acompañar a emprendedores y empresas tecnológicas.",
    summary:
      "La Ciudad inauguró un espacio de formación en inteligencia artificial aplicada a negocios y servicios públicos, con talleres gratuitos para PYMES de comercio electrónico, logística y turismo.",
    bullets: [
      "Esperan capacitar a 5.000 personas en el primer año.",
      "Habrá convenios con universidades y empresas tecnológicas.",
      "Se ofrecerán mentorías para proyectos en marcha.",
      "Funcionará en el Distrito Tecnológico de Parque Patricios.",
    ],
    body: "",
    image: "https://example.com/images/centro-ia.jpg",
    topic: "Gobierno de la Ciudad",
    bias: { left: 25, center: 55, right: 20 },
    sources: [
      {
        id: "lanacion_centro_ia",
        source: "La Nación",
        title: "La Ciudad lanza un centro de inteligencia artificial para PYMES",
        description: "",
        url: "https://lanacion.com.ar/tecnologia/centro-ia-pymes-caba",
        image: null,
        publishedAt: "2025-11-17T08:10:00Z",
        text: "Durante la presentación, el jefe de Gobierno destacó la necesidad de capacitar en IA...",
      },
    ],
    tags: ["Tecnología", "IA", "PYMES"],
  },
  {
    id: "cluster_salud_mental_guardias",
    createdAt: "2025-11-17T08:30:00Z",
    headline: "Refuerzan equipos de salud mental en guardias porteñas",
    subtitle: "Buscan mejorar la atención durante crisis y situaciones de violencia urbana.",
    summary:
      "La Ciudad incorporará psicólogos y psiquiatras en las guardias de hospitales generales para brindar contención ante episodios de pánico, violencia y consumo problemático. El plan se implementará de manera gradual hasta marzo.",
    bullets: [
      "Guardias recibirán especialistas durante 24 horas.",
      "Se trabajará en conjunto con SAME y defensa civil.",
      "Crece el número de consultas vinculadas al estrés.",
      "Organizaciones sociales celebran la medida y piden prevención.",
    ],
    body: "",
    image: "https://example.com/images/salud-mental-guardia.jpg",
    topic: "Servicios & Tarifas",
    bias: { left: 40, center: 45, right: 15 },
    sources: [
      {
        id: "pagina12_salud_mental",
        source: "Página/12",
        title: "Guardias porteñas suman equipos de salud mental",
        description: "",
        url: "https://pagina12.com.ar/sociedad/salud-mental-guardias",
        image: null,
        publishedAt: "2025-11-17T08:20:00Z",
        text: "El Ministerio de Salud porteño informó que se reforzarán las guardias...",
      },
    ],
    tags: ["Salud", "Guardias", "Contención"],
  },
  {
    id: "cluster_cultura_plazas_verano",
    createdAt: "2025-11-17T08:45:00Z",
    headline: "Plazas porteñas suman programación cultural gratuita en verano",
    subtitle: "Habrá cine, música y talleres itinerantes en 15 barrios.",
    summary:
      "El Ministerio de Cultura de la Ciudad anunció ciclos culturales al aire libre durante enero y febrero, con shows y talleres en plazas y parques y fuerte presencia de artistas locales.",
    bullets: [
      "El calendario arranca el 10 de enero.",
      "Participarán 120 artistas independientes.",
      "Habrá propuestas para niños y adultos mayores.",
      "Las actividades requerirán reserva previa online.",
    ],
    body: "",
    image: "https://example.com/images/plaza-cultural.jpg",
    topic: "Gobierno de la Ciudad",
    bias: { left: 30, center: 50, right: 20 },
    sources: [
      {
        id: "telam_cultura_plazas",
        source: "Télam",
        title: "La Ciudad anunció programación cultural gratuita en plazas",
        description: "",
        url: "https://telam.com.ar/cultura/plazas-programacion",
        image: null,
        publishedAt: "2025-11-17T08:40:00Z",
        text: "Desde el Ministerio de Cultura informaron que se realizarán shows gratuitos...",
      },
    ],
    tags: ["Cultura", "Verano", "Espacio Público"],
  },
  {
    id: "cluster_transporte_bicisendas_sur",
    createdAt: "2025-11-17T09:00:00Z",
    headline: "Extienden bicisendas en el corredor norte-sur de la Ciudad",
    subtitle: "La obra conectará Chacarita con Constitución y sumará 10 km de red.",
    summary:
      "Comenzó la construcción de una bicisenda que unirá Chacarita con Constitución, mejorando el corredor norte-sur y conectando con 20 estaciones Ecobici. Estará lista en marzo.",
    bullets: [
      "El corredor tendrá carriles protegidos y señalización LED.",
      "Se sumarán dársenas para repartidores.",
      "Habrá obras de arbolado y veredas nuevas.",
      "Los vecinos podrán seguir el avance en una web pública.",
    ],
    body: "",
    image: "https://example.com/images/bicisenda.jpg",
    topic: "Transporte & Movilidad",
    bias: { left: 25, center: 55, right: 20 },
    sources: [
      {
        id: "clarin_bicisenda",
        source: "Clarín",
        title: "La Ciudad extiende bicisendas hacia el sur",
        description: "",
        url: "https://clarin.com/ciudad/bicisendas-sur",
        image: null,
        publishedAt: "2025-11-17T08:55:00Z",
        text: "La obra conectará barrios históricamente relegados del sistema de ciclovías...",
      },
    ],
    tags: ["Bicisendas", "Movilidad", "Obras"],
  },
  {
    id: "cluster_seguridad_camaras",
    createdAt: "2025-11-17T09:15:00Z",
    headline: "La Ciudad suma 2.000 cámaras con IA para monitorear accesos",
    subtitle: "El plan incluye analítica para detectar autos con pedido de captura.",
    summary:
      "Se incorporarán 2.000 cámaras con reconocimiento de matrículas en accesos a la Ciudad y corredores críticos del GBA. Las imágenes se integrarán al Centro de Monitoreo Urbano.",
    bullets: [
      "La instalación finalizará en mayo.",
      "Trabajan en un protocolo de resguardo de datos.",
      "Las cámaras alertarán al SAME ante choques.",
      "Opositores piden auditoría independiente.",
    ],
    body: "",
    image: "https://example.com/images/camaras-seguridad.jpg",
    topic: "Seguridad",
    bias: { left: 28, center: 50, right: 22 },
    sources: [
      {
        id: "tn_seguridad_camaras",
        source: "TN",
        title: "Nuevas cámaras con IA para controlar accesos a la Ciudad",
        description: "",
        url: "https://tn.com.ar/seguridad/camaras-ia-accesos",
        image: null,
        publishedAt: "2025-11-17T09:05:00Z",
        text: "El gobierno porteño anunció la incorporación de tecnología de IA en la red de cámaras...",
      },
    ],
    tags: ["Seguridad", "Tecnología"],
  },
  {
    id: "cluster_servicios_agua_norte",
    createdAt: "2025-11-17T09:30:00Z",
    headline: "AySA reemplaza cañerías en Núñez y Belgrano para mejorar presión",
    subtitle: "Las obras demandarán cortes programados pero prometen mejoras para 80 mil vecinos.",
    summary:
      "AySA inició un plan de renovación de cañerías en Núñez y Belgrano para mejorar la presión del agua en verano. Los trabajos se coordinarán con cortes nocturnos y provisión de camiones cisterna.",
    bullets: [
      "Se intervendrán 12 km de red en 90 días.",
      "Habrá puestos de hidratación en plazas.",
      "Los trabajos se informarán por WhatsApp oficial.",
      "Comerciantes piden cronograma detallado.",
    ],
    body: "",
    image: "https://example.com/images/aysa-obra.jpg",
    topic: "Servicios & Tarifas",
    bias: { left: 35, center: 45, right: 20 },
    sources: [
      {
        id: "clarin_servicios_agua",
        source: "Clarín",
        title: "AySA inicia obras en Núñez y Belgrano: habrá cortes nocturnos",
        description: "",
        url: "https://clarin.com/ciudad/aysa-obras-nunez-belgrano",
        image: null,
        publishedAt: "2025-11-17T09:20:00Z",
        text: "AySA detalló que renovará cañerías antiguas para mejorar la presión...",
      },
    ],
    tags: ["AySA", "Obras", "Servicios"],
  },
  {
    id: "cluster_economia_creditos_verdes",
    createdAt: "2025-11-17T09:45:00Z",
    headline: "Lanzan créditos verdes para pymes del AMBA",
    subtitle: "Los préstamos financiarán eficiencia energética y paneles solares.",
    summary:
      "El Banco Ciudad presentó una línea de créditos verdes para pymes del AMBA que busquen instalar paneles solares o renovar equipos eficientes. Tendrán tasa subsidiada y asesoría técnica.",
    bullets: [
      "La tasa será 20% menor que la línea tradicional.",
      "Se financiarán proyectos hasta $80 millones.",
      "Habrá una ventanilla especial en Parque Patricios.",
      "Industriales piden ampliar cupo para logística.",
    ],
    body: "",
    image: "https://example.com/images/creditos-verdes.jpg",
    topic: "Economía & Precios",
    bias: { left: 30, center: 50, right: 20 },
    sources: [
      {
        id: "ambito_creditos_verdes",
        source: "Ámbito",
        title: "El Banco Ciudad lanza créditos verdes para pymes",
        description: "",
        url: "https://ambito.com/finanzas/creditos-verdes-banco-ciudad",
        image: null,
        publishedAt: "2025-11-17T09:35:00Z",
        text: "La entidad detalló que la línea financiará proyectos sustentables en el AMBA...",
      },
    ],
    tags: ["Créditos", "PYMES", "Sustentabilidad"],
  },
  {
    id: "cluster_transito_autopistas_digital",
    createdAt: "2025-11-17T10:00:00Z",
    headline: "Las autopistas porteñas suman tickets digitales para infracciones",
    subtitle: "Permitirá consultar online las multas y pagarlas con descuento.",
    summary:
      "AUSA lanzó un sistema de tickets digitales para infracciones en autopistas Illia, 25 de Mayo y Perito Moreno. Los usuarios recibirán notificaciones por mail y tendrán 10 días para pagar con descuento.",
    bullets: [
      "El sistema se integra con MiBA y la app de Autopistas Urbanas.",
      "Los datos se actualizarán en 24 horas.",
      "Habrá tutores virtuales para consultas.",
      "Usuarios piden simplificar el proceso de descargo.",
    ],
    body: "",
    image: "https://example.com/images/autopista-control.jpg",
    topic: "Transporte & Movilidad",
    bias: { left: 22, center: 58, right: 20 },
    sources: [
      {
        id: "infobae_autopistas_digital",
        source: "Infobae",
        title: "AUSA lanza tickets digitales para multas en autopistas",
        description: "",
        url: "https://infobae.com/economia/autopistas-tickets-digitales",
        image: null,
        publishedAt: "2025-11-17T09:55:00Z",
        text: "Autopistas Urbanas informó que desde esta semana las infracciones se notifican de forma digital...",
      },
    ],
    tags: ["Autopistas", "Tránsito", "Digitalización"],
  },
  {
    id: "cluster_obras_parque_costanera",
    createdAt: "2025-11-17T10:15:00Z",
    headline: "Avanzan obras del Parque de la Costanera Sur con nuevos miradores",
    subtitle: "El proyecto recupera sectores junto al río con senderos y puntos gastronómicos.",
    summary:
      "El Gobierno porteño informó que las obras del Parque de la Costanera Sur alcanzaron el 60% de avance, con la construcción de miradores, senderos y áreas de descanso. El parque abrirá por etapas desde abril.",
    bullets: [
      "Habrá 4 miradores elevados y nueva iluminación LED.",
      "El parque conectará con la Reserva Ecológica.",
      "Se sumarán locales gastronómicos y baños públicos.",
      "Organizaciones ambientales piden un plan de mantenimiento.",
    ],
    body: "",
    image: "https://example.com/images/parque-costanera.jpg",
    topic: "Obras & Urbanismo",
    bias: { left: 30, center: 55, right: 15 },
    sources: [
      {
        id: "lanacion_parque_costanera",
        source: "La Nación",
        title: "Cómo avanza el nuevo parque en Costanera Sur",
        description: "",
        url: "https://lanacion.com.ar/ciudad/parque-costanera-avance",
        image: null,
        publishedAt: "2025-11-17T10:05:00Z",
        text: "La Ciudad mostró los avances del parque que recupera los terrenos de la ex Ciudad Deportiva...",
      },
    ],
    tags: ["Costanera", "Parques", "Obras"],
  },
];

export const MOCK_POPULAR_NEWS: PopularNewsTab = [
  { id: "cluster_subte_dic_2025", title: "El SUBTE aumentará 15% desde diciembre" },
  { id: "cluster_inflacion_oct_2025", title: "La inflación de octubre fue 8,1%" },
  { id: "cluster_gba_basura", title: "Municipios del GBA refuerzan limpieza tras temporal" },
  { id: "cluster_salud_mental_guardias", title: "Guardias porteñas suman equipos de salud mental" },
  { id: "cluster_cultura_plazas_verano", title: "Plazas porteñas tendrán agenda cultural" },
  { id: "cluster_transporte_bicisendas_sur", title: "Extienden bicisendas norte-sur" },
];
