export type RawArticle = {
  source: string; // "Infobae"
  title?: string;
  description?: string;
  url?: string;
  image?: string | null;
  publishedAt?: string;
  contentHTML?: string; // full HTML if scraping
};

export type Article = {
  id: string; // hashed from url or similar
  source: string; // publisher name
  title: string;
  description?: string;
  url: string;
  image?: string | null;
  publishedAt: string;
  text: string; // cleaned plain text extracted from contentHTML
};

export type BiasBreakdown = {
  left: number; // e.g. 22
  center: number; // e.g. 53
  right: number; // e.g. 25
};

export type Topic =
  | "Economía & Precios"
  | "Transporte & Movilidad"
  | "Seguridad"
  | "Gobierno de la Ciudad"
  | "Provincia de Buenos Aires"
  | "Servicios & Tarifas"
  | "Obras & Urbanismo";

export type StoryCluster = {
  id: string; // unique ID for this cluster
  createdAt: string; // ISO date when cluster was generated

  // ---- Editorial Output (generated by your AI) ----
  headline: string; // rewritten neutral title (BA Sin Filtro)
  subtitle: string; // 1-2 lines context
  summary: string; // short paragraph summary
  bullets: string[]; // Axios-style bullet points
  body: string; // full neutral rewritten article
  image: string | null; // best image selected from sources

  // ---- Metadata ----
  topic: Topic; // the AMBA category
  bias: BiasBreakdown; // L/C/R percentages
  sources: Article[]; // original articles used

  // ---- Optional extras ----
  tags?: string[]; // subtopics or key entities (e.g. "Inflación", "SUBTE")
};

export type PopularNewsTab = { id: string; title: string }[];

export type GridArticle = {
  id: string;
  headline: string;
  image: string;
  bias: BiasBreakdown;
  topic: string;
  publishers?: string[];
  createdAt: string;
  summary?: string;
  caption?: string;
  whyItMatters?: string;
  primarySourceUrl?: string;
  subtitle?: string;
  body?: string;
  bullets?: string[];
  tags?: string[];
  sources?: Article[];
};

export type ArticleDetails = GridArticle & {
  subtitle: string;
  body: string;
  bullets: string[];
  tags: string[];
};
