export type RawArticle = {
  source: string; // "Infobae"
  title?: string;
  description?: string;
  url?: string;
  image?: string | null;
  publishedAt?: string;
  contentHTML?: string; // full HTML if scraping
  contentText?: string; // cleaned text version of contentHTML
};

export type FeedSource = {
  id: string;
  title: string;
  feedUrl: string;
  topic: Topic;
  region?: "CABA" | "PBA";
};

export type FeedArticle = RawArticle & {
  feedId: string;
  topic: Topic;
  region?: "CABA" | "PBA";
};

export type Article = {
  id: string; // hashed from url or similar
  source: string; // publisher name
  title: string;
  description?: string;
  url: string;
  image?: string | null;
  publishedAt: string;
  text: string; // cleaned plain text extracted from contentHTML
};

export type BiasBreakdown = {
  left: number; // e.g. 22
  center: number; // e.g. 53
  right: number; // e.g. 25
};

export type ArticleAxiomType =
  | "whats-new"
  | "why-it-matters"
  | "big-picture"
  | "by-the-numbers"
  | "how-it-works"
  | "between-the-lines"
  | "yes-but"
  | "what-to-watch"
  | "whats-next"
  | "bottom-line"
  | "go-deeper"
  | "driving-the-news"
  | "state-of-play"
  | "zoom-in"
  | "zoom-out"
  | "what-theyre-saying"
  | "threat-level"
  | "reality-check"
  | "the-other-side"
  | "the-intrigue";

export type ArticleAxiomBlock = {
  type: ArticleAxiomType;
  title?: string;
  text: string;
  bullets?: string[];
};

export type Topic =
  | "Política y Gobierno"
  | "Economía"
  | "Salud"
  | "Negocios"
  | "Tecnología"
  | "Ciencia"
  | "Educación"
  | "CABA"
  | "Buenos Aires (PBA)";

export type StoryCluster = {
  id: string; // unique ID for this cluster
  createdAt: string; // ISO date when cluster was generated

  // ---- Editorial Output (generated by your AI) ----
  headline: string; // rewritten neutral title (BA Sin Filtro)
  subtitle: string; // 1-2 lines context
  lede: string; // Smart Brevity lede paragraph
  axiomBlocks: ArticleAxiomBlock[]; // structured Smart Brevity blocks
  image: string | null; // best image selected from sources

  // ---- Metadata ----
  topic: Topic; // the AMBA category
  region?: "CABA" | "PBA";
  bias: BiasBreakdown; // L/C/R percentages
  sources: Article[]; // original articles used

  // ---- Optional extras ----
  tags?: string[]; // subtopics or key entities (e.g. "Inflación", "SUBTE")
};

export type PopularNewsTabItem = {
  id: string;
  title: string;
  targetTopic: Topic;
};

export type PopularNewsTab = PopularNewsTabItem[];

export type TopicTrend = "up" | "down" | "stable";

export type TopicQuickFact = {
  label: string;
  value: string;
  helper?: string;
  trend?: TopicTrend;
  tone?: "positive" | "negative" | "neutral";
};

export type TopicNeed = {
  title: string;
  detail: string;
};

export type TopicWatchItem = {
  label: string;
  description: string;
  impact: string;
};

export type TopicBrief = {
  title: string;
  description: string;
};

export type TopicPlaybook = {
  title: string;
  audience: string;
  description: string;
};

export type TopicQuestion = {
  question: string;
  answer: string;
};

export type PopularTopicPageContent = PopularNewsTabItem & {
  slug: string;
  heroKicker: string;
  heroDescription: string;
  heroUpdatedAt: string;
  heroInsight: string;
  narrative: TopicBrief[];
  audienceNeeds: TopicNeed[];
  watchlist: TopicWatchItem[];
  quickFacts: TopicQuickFact[];
  actionCard: TopicBrief & {
    actionLabel?: string;
    actionHref?: string;
  };
  playbooks: TopicPlaybook[];
  qas: TopicQuestion[];
};

export type GridArticle = {
  id: string;
  headline: string;
  image: string;
  bias: BiasBreakdown;
  topic: string;
  region?: "CABA" | "PBA";
  publishers?: string[];
  createdAt: string;
  lede?: string;
  caption?: string;
  whyItMatters?: string;
  primarySourceUrl?: string;
  subtitle?: string;
  axiomBlocks?: ArticleAxiomBlock[];
  tags?: string[];
  sources?: Article[];
};

export type ArticleDetails = GridArticle & {
  lede: string;
  axiomBlocks: ArticleAxiomBlock[];
  tags: string[];
};
